# Generated by Django 4.2.3 on 2023-08-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_country_alter_adress_options_book_published_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
